# fly.toml app configuration file generated for geo-audit-nico on 2026-03-24T16:56:54-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'geo-audit-nico'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
